# Generated by Django 5.2.9 on 2026-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPatterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(blank=True, max_length=200, null=True)),
                ('permsissionpattern', models.CharField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
