# Generated by Django 5.2.9 on 2026-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apppatterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphistory',
            name='binary_vector',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='confidence',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='granted_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='packageName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='permission_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='prediction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apphistory',
            name='risk_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='apphistory',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apphistory',
            name='app_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
