# Generated by Django 5.2.9 on 2026-01-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apphistory_binary_vector_apphistory_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphistory',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
