# Generated by Django 5.2.9 on 2026-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apphistory_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('breach_name', models.CharField(max_length=200)),
                ('breach_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['email', '-detected_at'], name='api_breachh_email_26844f_idx'), models.Index(fields=['user', '-detected_at'], name='api_breachh_user_1d145b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='api_userpro_email_4cfe15_idx')],
            },
        ),
    ]
