# Generated by Django 5.2.9 on 2026-01-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_breachhistory_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBreachHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('breach_name', models.CharField(max_length=200)),
                ('breach_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='phishingurlhistory',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AddField(
            model_name='phishingurlhistory',
            name='confidence_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='phishingurlhistory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingurlhistory',
            name='is_phishing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phishingurlhistory',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing'), ('malware', 'Malware')], default='safe', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phishingurlhistory',
            name='threats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='phishingurlhistory',
            index=models.Index(fields=['url'], name='api_phishin_url_c28fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='phishingurlhistory',
            index=models.Index(fields=['user', '-detected_at'], name='api_phishin_user_dd6ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebreachhistory',
            index=models.Index(fields=['phone', '-detected_at'], name='api_phonebr_phone_8c23fd_idx'),
        ),
        migrations.AddIndex(
            model_name='phonebreachhistory',
            index=models.Index(fields=['user', '-detected_at'], name='api_phonebr_user_e7a0dc_idx'),
        ),
    ]
