# Generated by Django 5.2.9 on 2026-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_phonebreachhistory_alter_phishingurlhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breachhistory',
            name='data_classes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_malware_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_spam_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_subscription_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='logo_path',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='breachhistory',
            name='pwn_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
